### ISSUE TITLE
Doesnt Works On IOS 12.5.6

### ISSUE THREAD

**Issue by Devof73** [YuzuZensai/iOS-DiscordPresence#2]
Respring inmediatly after launching a app.

**Comment by YuzuZensai** [comment]
Can you provide more information? Such as your device model, jailbreaking method, or a crash log

**Comment by Devof73** [comment]
This is the log.
[log_springboard_101122.txt](https://github.com/YuzuZensai/iOS-DiscordPresence/files/9997683/log_springboard_101122.txt)

**Comment by YuzuZensai** [comment]
Seem like that ``[SBApplicationInfo iTunesCategoriesOrderedByRelevancy]`` property only exists after iOS 14.
Since that only property is only use to detect the application is game or not. There might be some workarounds (no guarantees), but I don't have any device with iOS that's lower than 14, this might take awhile.

**Comment by YuzuZensai** [comment]
Fixed in 56408b59648c21004221bd4252c81e03dffb4ea3 by implementing temporary workaround and released in [0.0.2](https://github.com/YuzuZensai/iOS-DiscordPresence/releases/0.0.2)
